if: branch = master and not type IN (pull_request)
dist: trusty
sudo: false
language: minimal
before_install: true
install: true
before_script: true
script:
- echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin
- echo ${TRAVIS_BUILD_NUMBER} > version
- echo ${TRAVIS_COMMIT} >> version
- docker build  --no-cache -t fiware/service.orionexporter .
- docker push fiware/service.orionexporter
notifications:
  webhooks:
    urls:
      secure: v+Q6qfUCKezzUEbSdCntkNajIzxoqB/c+U2nxm6a9CE0S16QTmyNzBuUrNngN5pyBkMmfGV4LSqekF+UWmtL2FHwYZg4T4tQUiMlyzzB5CfETOgkMlJbRp8TK6/CLKSrAxLFyvNIQVNrYUrxYiPRgMJW02C5EabmexGOaN1eKj46KVMQsRaCyyUz2pEd6D9HxmdE1iP4d1F0j6EIC7PVCxvwj6G2LnkUNMJgaY5UWDzhzAJpTVnLU+1elDYz81Quhol0iOVRs+8tbxODMKpeHQdcJZ1PToOzYinLPOgs6S5mMZe3EfB32NaznTWyk01LjSUGLiE80QCsAku8ooLyDmYDL/p7kURZ73AtCzpCGhSGQoUIRp/sVYDEHJeeMVvl3N30Wqd8GT5IcYb+dKKHGbuU1EhBO4WhffYNrHcThLaJeGwA4gd6hLYvY8e2k6zxd6NNMxZzoPyQ6lUXqwwEkN1/0mofpZFcy6/QYYuWb1oNgD2C2NKfR6v7YnJp9qiDIp0r0Mg1xl31rCHKtim9DufvqfG+TNSpmnG7D7/tUqJxeB9ybMzFu72tSEKbBZSZ1U/tPCGGmB+qUeb0Hsd4O6IPMdWhOZ1Ev5M5NP20nU5YzZQg0eeekeGQ/ZlEogwV66X7bBUcwkIPUst94p7bkFccCWAM0gWupoTp7smwNvU=
